/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import java.util.Arrays;
import MODEL.*;
import CONTROLLER.*;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.stream.DoubleStream;
import javax.swing.JOptionPane;
/**
 *
 * @author MASS MNM
 */
public class Batsman_SelectionFrm extends javax.swing.JFrame {
private MasterDB MasterDB;
    /**
     * Creates new form Batsman_SelectionFrm
     */
    public Batsman_SelectionFrm() {
        initComponents();
         MasterDB=new MasterDB();
    }
 private boolean isValidate(){ //Validate change into isValidate
       
        if (txtplayername.getText().equals(""))  
        {
            JOptionPane.showMessageDialog(rootPane, "Player Name is a requied field");  //help message
            txtplayername.requestFocusInWindow();
            return false;
        }
        if (txtnationality.getText().equals(""))  
        {
            JOptionPane.showMessageDialog(rootPane, "Nationality  is a requied field");  //help message
            txtnationality.requestFocusInWindow();
            return false;
        }
        if (txtsrate.getText().equals("")) //flag=false;
        {
            JOptionPane.showMessageDialog(rootPane, "Batting Strike Rate is a requied field");   
            txtsrate.requestFocusInWindow();
            return false;
        }
        if (txtaverage.getText().equals("")) //flag=false;
        {
            JOptionPane.showMessageDialog(rootPane, "Batting Average is a requied field");  
            txtaverage.requestFocusInWindow();
            return false;
        }
        if (txtteamid.getText().equals("")) //flag=false;
        {
            JOptionPane.showMessageDialog(rootPane, "Team ID is a requied field");  
            txtteamid.requestFocusInWindow();
            return false;
        }
        if (txtteamname.getText().equals("")) //flag=false;
        {
            JOptionPane.showMessageDialog(rootPane, "Team Name is a requied field");  
            txtteamname.requestFocusInWindow();
            return false;
        }
        if (txtinnings.getText().equals("")) //flag=false;
        {
            JOptionPane.showMessageDialog(rootPane, "Inninga is a requied field");  
            txtinnings.requestFocusInWindow();
            return false;
        }
       if (txttotmatch.getText().equals("")) //flag=false;
        {
            JOptionPane.showMessageDialog(rootPane, "Total Match is a requied field");  
            txttotmatch.requestFocusInWindow();
            return false;
        }
        return true;
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtaverage = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtsrate = new javax.swing.JTextField();
        btnadd = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        lblExistingSrate = new javax.swing.JLabel();
        lblexistingAverage = new javax.swing.JLabel();
        txtSWeights = new javax.swing.JTextField();
        txtAWeights = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNewW1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNewW2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cmbprole = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtnationality = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txttotmatch = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtinnings = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txthighscore = new javax.swing.JTextField();
        txtprocess = new javax.swing.JButton();
        txtteamid = new javax.swing.JTextField();
        txtteamname = new javax.swing.JTextField();
        txtplayername = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(850, 620));
        setMinimumSize(new java.awt.Dimension(850, 620));
        setPreferredSize(new java.awt.Dimension(850, 620));
        getContentPane().setLayout(null);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Strike Rate");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 240, 90, 20);

        txtaverage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtaverageKeyTyped(evt);
            }
        });
        getContentPane().add(txtaverage);
        txtaverage.setBounds(220, 280, 180, 29);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Average");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(120, 280, 90, 20);

        txtsrate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtsrateKeyTyped(evt);
            }
        });
        getContentPane().add(txtsrate);
        txtsrate.setBounds(220, 240, 180, 29);

        btnadd.setText("ADD");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });
        getContentPane().add(btnadd);
        btnadd.setBounds(440, 530, 94, 34);

        btnclear.setText("CLEAR");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        getContentPane().add(btnclear);
        btnclear.setBounds(670, 530, 94, 34);

        lblExistingSrate.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblExistingSrate);
        lblExistingSrate.setBounds(220, 420, 260, 30);

        lblexistingAverage.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblexistingAverage);
        lblexistingAverage.setBounds(220, 460, 270, 30);

        txtSWeights.setEditable(false);
        getContentPane().add(txtSWeights);
        txtSWeights.setBounds(220, 320, 180, 30);

        txtAWeights.setEditable(false);
        getContentPane().add(txtAWeights);
        txtAWeights.setBounds(220, 360, 180, 30);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Strike Rate Weights");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(100, 320, 110, 20);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Average Weights");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(100, 360, 100, 20);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("==>");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(420, 330, 46, 20);

        txtNewW1.setEditable(false);
        getContentPane().add(txtNewW1);
        txtNewW1.setBounds(490, 320, 180, 29);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("==>");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(420, 370, 40, 20);

        txtNewW2.setEditable(false);
        getContentPane().add(txtNewW2);
        txtNewW2.setBounds(490, 360, 180, 28);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Player Role");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(120, 110, 90, 20);

        cmbprole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BATSMAN" }));
        getContentPane().add(cmbprole);
        cmbprole.setBounds(220, 110, 180, 30);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Nationality");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(120, 150, 90, 20);

        txtnationality.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnationalityActionPerformed(evt);
            }
        });
        getContentPane().add(txtnationality);
        txtnationality.setBounds(220, 150, 180, 32);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Total Match");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(120, 200, 90, 20);

        txttotmatch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txttotmatchKeyTyped(evt);
            }
        });
        getContentPane().add(txttotmatch);
        txttotmatch.setBounds(220, 200, 180, 31);

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Innings");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(420, 160, 90, 20);

        txtinnings.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtinningsKeyTyped(evt);
            }
        });
        getContentPane().add(txtinnings);
        txtinnings.setBounds(510, 160, 180, 31);

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("High Score");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(420, 200, 90, 20);
        getContentPane().add(txthighscore);
        txthighscore.setBounds(510, 200, 180, 29);

        txtprocess.setText("PROCESS");
        txtprocess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprocessActionPerformed(evt);
            }
        });
        getContentPane().add(txtprocess);
        txtprocess.setBounds(560, 530, 92, 34);

        txtteamid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtteamidActionPerformed(evt);
            }
        });
        getContentPane().add(txtteamid);
        txtteamid.setBounds(510, 70, 180, 30);

        txtteamname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtteamnameActionPerformed(evt);
            }
        });
        getContentPane().add(txtteamname);
        txtteamname.setBounds(510, 110, 180, 30);
        getContentPane().add(txtplayername);
        txtplayername.setBounds(220, 70, 180, 30);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("NEW BATSMAN FORMS");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(240, 20, 280, 20);

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Team ID");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(420, 80, 70, 20);

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Player Name");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(120, 70, 90, 20);

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Team Name");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(420, 120, 90, 20);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 40, 800, 10);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/BS.jpg"))); // NOI18N
        jLabel15.setText("jLabel15");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(-20, 0, 850, 580);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        if(isValidate()){
            
       
           double []ExistingTot_SRate = new double[150];
           double []ExistingTot_Ave  = new double[150];
           int x=0;
        
        
        
       // tblModel.setRowCount(0);
        String PName=cmbprole.getSelectedItem().toString();
        ArrayList<PlayersList> pList=MasterDB.GetBatsman(PName);
        
        for(PlayersList atn:pList){
                
         ExistingTot_SRate[x] = Double.parseDouble(atn.getSPerfact_Weight());
         ExistingTot_Ave  [x] = Double.parseDouble(atn.getAPerfact_Weight());
           x++;
        }
        
        double s= DoubleStream.of(ExistingTot_SRate).sum()/100;
        double b= DoubleStream.of(ExistingTot_Ave).sum()/100;
          
    
       
            double k = Double.parseDouble(txtsrate.getText());
            double x1 = 1/k;
            double m = Double.parseDouble(txtaverage.getText());
            double y1 = 1/m;
           
           
            
             Train_Neural predvalue= new Train_Neural();
            
            predvalue.getSrate(x1,1);
            predvalue.getAverage(y1, 1);
            predvalue.RandomMethodSrate();
            predvalue.RandomMethodAverage();
            predvalue.SumFunction();
            predvalue.SumFunction1();
            predvalue.Activate();
            predvalue.TrainingNetwork_Srate(0);
            predvalue.TrainingNetwork_Average(0);
       
       
 
          int z=0;
           
           while((z<100)){
           predvalue.TrainingNetwork_Srate(1);
           predvalue.TrainingNetwork_Average(1);
           predvalue.SumFunction();
           predvalue.SumFunction1();
           predvalue.Activate();
             z++;
          }
           

           if(predvalue.error==0){
               
                 txtSWeights.setText(String.valueOf(predvalue.S_weights[0]));
                 txtAWeights.setText(String.valueOf(predvalue.A_weights[0]));
                
              DecimalFormat  df= new DecimalFormat("##.##");
                 
              txtNewW1.setText(df.format(predvalue.S_weights[0]*100)+" %");   
              txtNewW2.setText(df.format(predvalue.A_weights[0]*100)+" %");
              
              lblExistingSrate.setText("Predictable Batsman Strike Rate "+df.format(s*100)+" %");
              lblexistingAverage.setText("Predictable Batsman Avarage  "+df.format(b*100)+" %");
                 
           }
        }
        
    }//GEN-LAST:event_btnaddActionPerformed

    private void txtprocessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprocessActionPerformed
        // TODO add your handling code here:
       String  Team_ID=    txtteamid.getText();
       String  Team_Name=  txtteamname.getText();
       String  PlayerName= txtplayername.getText();
       String  Player_Role= cmbprole.getSelectedItem().toString();
       String  Nationality= txtnationality.getText();
       int     Total_Matchs= Integer.parseInt(txttotmatch.getText());
       int     Innigs= Integer.parseInt( txtinnings.getText());
       int     Highscore=Integer.parseInt(txthighscore.getText());
       int     totwicket= 0;
       double  Bat_Srate= Double.parseDouble(txtsrate.getText());
       double  Bat_Ave    = Double.parseDouble(txtaverage.getText());
       double  Bowl_Economy= 0.0;
       double  Bowl_Average= 0.0;
       int     Stumps= 0;
       int     Catchs= 0;
       String  Bat_SWeight= txtSWeights.getText();
       String  Bat_AWeight= txtAWeights.getText();
       String  Bowl_EWeight= null;
       String  Bowl_AWeight= null;
       String  Catch_Weight= null;
       String  Stump_Weight= null;
     
       
       Team_Players   team= new Team_Players(Team_ID, Team_Name, PlayerName, Player_Role, Nationality, Total_Matchs, Innigs, Highscore,totwicket, Bat_Srate, Bat_Ave, Bowl_Economy, Bowl_Average, Stumps,Catchs, Bat_SWeight, Bat_AWeight,Bowl_EWeight,Bowl_AWeight, Catch_Weight,Stump_Weight);
       
        int result= MasterDB.AddTeamPlayers(team);
            
            if(result>0){
                JOptionPane.showMessageDialog(rootPane, "Teams Player is added");
            }else{
                JOptionPane.showMessageDialog(rootPane, "Team Player is not added");
            }  
    }//GEN-LAST:event_txtprocessActionPerformed

    private void txtteamnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtteamnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtteamnameActionPerformed

    private void txtteamidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtteamidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtteamidActionPerformed

    private void txtnationalityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnationalityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnationalityActionPerformed

    private void txtinningsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtinningsKeyTyped
        // TODO add your handling code here:
         char c=evt.getKeyChar();
        if(c!='0' && c!='1' && c!='2' && c!='3' && c!='4' && c!='5' && c!='5' && c!='6' && c!='7' && c!='8' && c!='9' && c!='.')
            evt.consume();
    }//GEN-LAST:event_txtinningsKeyTyped

    private void txttotmatchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttotmatchKeyTyped
        // TODO add your handling code here:
         char c=evt.getKeyChar();
        if(c!='0' && c!='1' && c!='2' && c!='3' && c!='4' && c!='5' && c!='5' && c!='6' && c!='7' && c!='8' && c!='9' && c!='.')
            evt.consume();
    }//GEN-LAST:event_txttotmatchKeyTyped

    private void txtsrateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsrateKeyTyped
        // TODO add your handling code here:
         char c=evt.getKeyChar();
        if(c!='0' && c!='1' && c!='2' && c!='3' && c!='4' && c!='5' && c!='5' && c!='6' && c!='7' && c!='8' && c!='9' && c!='.')
            evt.consume();
    }//GEN-LAST:event_txtsrateKeyTyped

    private void txtaverageKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtaverageKeyTyped
        // TODO add your handling code here:
         char c=evt.getKeyChar();
        if(c!='0' && c!='1' && c!='2' && c!='3' && c!='4' && c!='5' && c!='5' && c!='6' && c!='7' && c!='8' && c!='9' && c!='.')
            evt.consume();
    }//GEN-LAST:event_txtaverageKeyTyped

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        // TODO add your handling code here:
         txtAWeights.setText("");
        txtNewW1.setText("");
        txtNewW2.setText("");
        txtSWeights.setText("");
        txtaverage.setText("");
        txthighscore.setText("");
        txtinnings.setText("");
        txtnationality.setText("");
        txtplayername.setText("");
        txtsrate.setText("");
        txtteamid.setText("");
        txtteamname.setText("");
        txttotmatch.setText("");
         
    }//GEN-LAST:event_btnclearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Batsman_SelectionFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Batsman_SelectionFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Batsman_SelectionFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Batsman_SelectionFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Batsman_SelectionFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnclear;
    private javax.swing.JComboBox<String> cmbprole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblExistingSrate;
    private javax.swing.JLabel lblexistingAverage;
    private javax.swing.JTextField txtAWeights;
    private javax.swing.JTextField txtNewW1;
    private javax.swing.JTextField txtNewW2;
    private javax.swing.JTextField txtSWeights;
    private javax.swing.JTextField txtaverage;
    private javax.swing.JTextField txthighscore;
    private javax.swing.JTextField txtinnings;
    private javax.swing.JTextField txtnationality;
    private javax.swing.JTextField txtplayername;
    private javax.swing.JButton txtprocess;
    private javax.swing.JTextField txtsrate;
    private javax.swing.JTextField txtteamid;
    private javax.swing.JTextField txtteamname;
    private javax.swing.JTextField txttotmatch;
    // End of variables declaration//GEN-END:variables
}
