/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import MODEL.*;
import MODEL.*;
import CONTROLLER.*;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.stream.DoubleStream;
import javax.swing.JOptionPane;

/**
 *
 * @author MASS MNM
 */
public class Bowler_SelectionFrm extends javax.swing.JFrame {
private MasterDB MasterDB;
    /**
     * Creates new form Bowler_SelectionFrm
     */
    public Bowler_SelectionFrm() {
        initComponents();
         MasterDB=new MasterDB();
    }
 private boolean isValidate(){ //Validate change into isValidate
       
        if (txtplayername.getText().equals(""))  
        {
            JOptionPane.showMessageDialog(rootPane, "Player Name is a requied field");  //help message
            txtplayername.requestFocusInWindow();
            return false;
        }
        if (txtteamid.getText().equals("")) //flag=false;
        {
            JOptionPane.showMessageDialog(rootPane, "Team ID is a requied field");  
            txtteamid.requestFocusInWindow();
            return false;
        }
        if (txtteamname.getText().equals("")) //flag=false;
        {
            JOptionPane.showMessageDialog(rootPane, "Team Name is a requied field");  
            txtteamname.requestFocusInWindow();
            return false;
        }
        if (txtnationality.getText().equals(""))  
        {
            JOptionPane.showMessageDialog(rootPane, "Nationality  is a requied field");  //help message
            txtnationality.requestFocusInWindow();
            return false;
        }
        if (txttotmatch.getText().equals("")) //flag=false;
        {
            JOptionPane.showMessageDialog(rootPane, "Total Matchs is a requied field");  
            txttotmatch.requestFocusInWindow();
            return false;
        }
        if (txtbecon.getText().equals("")) //flag=false;
        {
            JOptionPane.showMessageDialog(rootPane, "Bowling Economy is a requied field");  
            txtbecon.requestFocusInWindow();
            return false;
        }
        if (txtbaverg.getText().equals("")) //flag=false;
        {
            JOptionPane.showMessageDialog(rootPane, "Bowling Average is a requied field");  
            txtbaverg.requestFocusInWindow();
            return false;
        }
      
        return true;
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmbPRole = new javax.swing.JComboBox<>();
        txtbaverg = new javax.swing.JTextField();
        txtbecon = new javax.swing.JTextField();
        txteconweight = new javax.swing.JTextField();
        txtBAverWeight = new javax.swing.JTextField();
        lblNew1 = new javax.swing.JLabel();
        lblNew2 = new javax.swing.JLabel();
        txtPred2 = new javax.swing.JTextField();
        txtPred1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnadd = new javax.swing.JButton();
        btncancel = new javax.swing.JButton();
        btnprocess = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtwickets = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtnationality = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txttotmatch = new javax.swing.JTextField();
        txtplayername = new javax.swing.JTextField();
        txtteamid = new javax.swing.JTextField();
        txtteamname = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(860, 650));
        setMinimumSize(new java.awt.Dimension(860, 650));
        setPreferredSize(new java.awt.Dimension(860, 650));
        getContentPane().setLayout(null);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Bowling Economy");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 230, 100, 20);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Player Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(90, 90, 80, 20);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Bowling Average");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 280, 100, 22);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Economy Weights");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 330, 100, 20);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Average Weights");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(70, 370, 100, 20);

        cmbPRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BOWLER" }));
        getContentPane().add(cmbPRole);
        cmbPRole.setBounds(180, 130, 192, 40);

        txtbaverg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtbavergKeyTyped(evt);
            }
        });
        getContentPane().add(txtbaverg);
        txtbaverg.setBounds(180, 275, 193, 30);

        txtbecon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtbeconKeyTyped(evt);
            }
        });
        getContentPane().add(txtbecon);
        txtbecon.setBounds(180, 225, 193, 30);

        txteconweight.setEditable(false);
        getContentPane().add(txteconweight);
        txteconweight.setBounds(180, 322, 193, 30);

        txtBAverWeight.setEditable(false);
        getContentPane().add(txtBAverWeight);
        txtBAverWeight.setBounds(180, 370, 193, 29);

        lblNew1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblNew1);
        lblNew1.setBounds(180, 430, 268, 35);

        lblNew2.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblNew2);
        lblNew2.setBounds(180, 470, 268, 38);

        txtPred2.setEditable(false);
        getContentPane().add(txtPred2);
        txtPred2.setBounds(460, 370, 174, 33);

        txtPred1.setEditable(false);
        txtPred1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPred1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtPred1);
        txtPred1.setBounds(460, 320, 174, 31);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("==>");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(410, 330, 24, 14);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("==>");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(410, 380, 24, 14);

        btnadd.setText("ADD");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });
        getContentPane().add(btnadd);
        btnadd.setBounds(480, 530, 103, 41);

        btncancel.setText("CLEAR");
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });
        getContentPane().add(btncancel);
        btncancel.setBounds(720, 530, 98, 41);

        btnprocess.setText("PROCESS");
        btnprocess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprocessActionPerformed(evt);
            }
        });
        getContentPane().add(btnprocess);
        btnprocess.setBounds(600, 530, 101, 41);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Total Wickets");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(400, 240, 80, 20);

        txtwickets.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtwicketsKeyTyped(evt);
            }
        });
        getContentPane().add(txtwickets);
        txtwickets.setBounds(490, 230, 174, 35);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Nationality");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(80, 190, 80, 20);
        getContentPane().add(txtnationality);
        txtnationality.setBounds(180, 180, 192, 33);

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Team ID");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(410, 90, 70, 20);

        txttotmatch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txttotmatchKeyTyped(evt);
            }
        });
        getContentPane().add(txttotmatch);
        txttotmatch.setBounds(490, 180, 174, 35);
        getContentPane().add(txtplayername);
        txtplayername.setBounds(180, 80, 190, 30);
        getContentPane().add(txtteamid);
        txtteamid.setBounds(490, 80, 170, 30);
        getContentPane().add(txtteamname);
        txtteamname.setBounds(490, 130, 170, 30);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("NEW BOWLER FORMS");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(240, 20, 280, 20);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 40, 850, 10);

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Team Name");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(410, 140, 70, 20);

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Player Role");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(80, 140, 80, 20);

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Total Match");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(410, 190, 70, 20);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/BMS.jpg"))); // NOI18N
        jLabel11.setText("jLabel11");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, -20, 850, 620);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:
         if(isValidate()){  
        double  []ExistingTot_Econ = new double[150];
           double []ExistingTot_Ave  = new double[150];
           int x=0;
        
        
        
       // tblModel.setRowCount(0);
        String PName=cmbPRole.getSelectedItem().toString();
        ArrayList<BowlerList> bList=MasterDB.GetBowlers(PName);
        
        for(BowlerList atn:bList){
                
         ExistingTot_Econ[x] = Double.parseDouble(atn.getBEcon_Weight());
         ExistingTot_Ave  [x] = Double.parseDouble(atn.getBAve_Weight());
           x++;
        }
        
        double s= DoubleStream.of(ExistingTot_Econ).sum()/100;
        double b= DoubleStream.of(ExistingTot_Ave).sum()/100;
          
    
       
            double k = Double.parseDouble(txtbecon.getText());
            double x1 = 1/k;
            double m = Double.parseDouble(txtbaverg.getText());
            double y1 = 1/m;
           
           
            
             Train_Bowler predvalue= new Train_Bowler();
            
            predvalue.getEconInput(x1,1);
            predvalue.getAverageInput(y1, 1);
            predvalue.RandomMethodBEcon();
            predvalue.RandomMethodAverage();
            predvalue.SumFunction();
            predvalue.SumFunction1();
            predvalue.Activate();
            predvalue.TrainingNetwork_BEcon(0);
            predvalue.TrainingNetwork_Average(0);
       
       
 
          int z=0;
           
           while((z<100)){
           predvalue.TrainingNetwork_BEcon(1);
           predvalue.TrainingNetwork_Average(1);
           predvalue.SumFunction();
           predvalue.SumFunction1();
           predvalue.Activate();
             z++;
          }
           

           if(predvalue.error==0){
               
                 txteconweight.setText(String.valueOf(predvalue.Econ_weights[0]));
                 txtBAverWeight.setText(String.valueOf(predvalue.Ave_weights[0]));
                
              DecimalFormat  df= new DecimalFormat("##.##");
                 
              txtPred1.setText(df.format(predvalue.Econ_weights[0]*100)+" %");   
              txtPred2.setText(df.format(predvalue.Ave_weights[0]*100)+" %");
              
              lblNew1.setText("Predictable Batsman Strike Rate "+df.format(s*100)+" %");
              lblNew2.setText("Predictable Batsman Avarage  "+df.format(b*100)+" %");
                 
           }
         }
    }//GEN-LAST:event_btnaddActionPerformed

    private void btnprocessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprocessActionPerformed
        // TODO add your handling code here:
       String  Team_ID=    txtteamid.getText();
       String  Team_Name=  txtteamname.getText();
       String  PlayerName= txtplayername.getText();
       String  Player_Role= cmbPRole.getSelectedItem().toString();
       String  Nationality= txtnationality.getText();
       int     Total_Matchs= Integer.parseInt(txttotmatch.getText());
       int     Innigs= 0;
       int     Highscore=0;
       int     totwicket= Integer.parseInt( txtwickets.getText());
       double  Bat_Srate= 0.0;
       double  Bat_Ave    = 0.0;
       double  Bowl_Economy= Double.parseDouble(txtbecon.getText());
       double  Bowl_Average= Double.parseDouble(txtbaverg.getText());
       int     Stumps= 0;
       int     Catchs= 0;
       String  Bat_SWeight=null;
       String  Bat_AWeight= null;
       String  Bowl_EWeight= txteconweight.getText();
       String  Bowl_AWeight= txtBAverWeight.getText();
       String  Catch_Weight= null;
       String  Stump_Weight= null;
     
       
       Team_Players   team= new Team_Players(Team_ID, Team_Name, PlayerName, Player_Role, Nationality, Total_Matchs, Innigs, Highscore,totwicket, Bat_Srate, Bat_Ave, Bowl_Economy, Bowl_Average, Stumps,Catchs, Bat_SWeight, Bat_AWeight,Bowl_EWeight,Bowl_AWeight, Catch_Weight,Stump_Weight);
       
        int result= MasterDB.AddTeamPlayers(team);
            
            if(result>0){
                JOptionPane.showMessageDialog(rootPane, "Teams Player is added");
            }else{
                JOptionPane.showMessageDialog(rootPane, "Team Player is not added");
            }  
    }//GEN-LAST:event_btnprocessActionPerformed

    private void txtPred1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPred1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPred1ActionPerformed

    private void txtbeconKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbeconKeyTyped
        // TODO add your handling code here:
         char c=evt.getKeyChar();
        if(c!='0' && c!='1' && c!='2' && c!='3' && c!='4' && c!='5' && c!='5' && c!='6' && c!='7' && c!='8' && c!='9' && c!='.')
            evt.consume();
    }//GEN-LAST:event_txtbeconKeyTyped

    private void txtbavergKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbavergKeyTyped
        // TODO add your handling code here:
         char c=evt.getKeyChar();
        if(c!='0' && c!='1' && c!='2' && c!='3' && c!='4' && c!='5' && c!='5' && c!='6' && c!='7' && c!='8' && c!='9' && c!='.')
            evt.consume();
    }//GEN-LAST:event_txtbavergKeyTyped

    private void txttotmatchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttotmatchKeyTyped
        // TODO add your handling code here:
         char c=evt.getKeyChar();
        if(c!='0' && c!='1' && c!='2' && c!='3' && c!='4' && c!='5' && c!='5' && c!='6' && c!='7' && c!='8' && c!='9' && c!='.')
            evt.consume();
    }//GEN-LAST:event_txttotmatchKeyTyped

    private void txtwicketsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtwicketsKeyTyped
        // TODO add your handling code here:
         char c=evt.getKeyChar();
        if(c!='0' && c!='1' && c!='2' && c!='3' && c!='4' && c!='5' && c!='5' && c!='6' && c!='7' && c!='8' && c!='9' && c!='.')
            evt.consume();
    }//GEN-LAST:event_txtwicketsKeyTyped

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        // TODO add your handling code here:
        txtBAverWeight.setText("");
        txtPred1.setText("");
        txtPred2.setText("");
        txtbaverg.setText("");
        txtbecon.setText("");
        txteconweight.setText("");
        txtnationality.setText("");
        txtplayername.setText("");
        txtteamid.setText("");
        txtteamname.setText("");
        txttotmatch.setText("");
        txtwickets.setText("");
        
    }//GEN-LAST:event_btncancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bowler_SelectionFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bowler_SelectionFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bowler_SelectionFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bowler_SelectionFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bowler_SelectionFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btnprocess;
    private javax.swing.JComboBox<String> cmbPRole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblNew1;
    private javax.swing.JLabel lblNew2;
    private javax.swing.JTextField txtBAverWeight;
    private javax.swing.JTextField txtPred1;
    private javax.swing.JTextField txtPred2;
    private javax.swing.JTextField txtbaverg;
    private javax.swing.JTextField txtbecon;
    private javax.swing.JTextField txteconweight;
    private javax.swing.JTextField txtnationality;
    private javax.swing.JTextField txtplayername;
    private javax.swing.JTextField txtteamid;
    private javax.swing.JTextField txtteamname;
    private javax.swing.JTextField txttotmatch;
    private javax.swing.JTextField txtwickets;
    // End of variables declaration//GEN-END:variables
}
