/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import CONTROLLER.*;
import MODEL.*;
import javax.swing.JOptionPane;

/**
 *
 * @author MASS MNM
 */
public class ChangePassword_Frm extends javax.swing.JFrame {
   private Login_DB logDB;
    /**
     * Creates new form ChangePassword_Frm
     */
    public ChangePassword_Frm() {
        initComponents();
        logDB =new Login_DB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        txtUName = new javax.swing.JTextField();
        txtoldPwd = new javax.swing.JPasswordField();
        txtNewPWD = new javax.swing.JPasswordField();
        txtconfirmPwd = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnupdate = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(570, 355));
        setMinimumSize(new java.awt.Dimension(570, 355));
        setPreferredSize(new java.awt.Dimension(570, 355));
        getContentPane().setLayout(null);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(10, 50, 550, 10);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setOpaque(false);
        jPanel1.setLayout(null);
        jPanel1.add(txtUName);
        txtUName.setBounds(160, 40, 171, 30);
        jPanel1.add(txtoldPwd);
        txtoldPwd.setBounds(160, 80, 171, 30);
        jPanel1.add(txtNewPWD);
        txtNewPWD.setBounds(160, 120, 171, 30);
        jPanel1.add(txtconfirmPwd);
        txtconfirmPwd.setBounds(160, 160, 171, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("User Name");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 40, 110, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Old Password");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 80, 110, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("New Password");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 120, 110, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Confirm Password");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 160, 101, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 74, 360, 230);

        btnupdate.setBackground(new java.awt.Color(0, 0, 0));
        btnupdate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnupdate.setForeground(new java.awt.Color(255, 255, 255));
        btnupdate.setText("UPDATE");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnupdate);
        btnupdate.setBounds(430, 150, 95, 30);

        btnclear.setBackground(new java.awt.Color(0, 0, 0));
        btnclear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnclear.setForeground(new java.awt.Color(255, 255, 255));
        btnclear.setText("CLEAR");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        getContentPane().add(btnclear);
        btnclear.setBounds(430, 200, 95, 30);

        jLabel6.setFont(new java.awt.Font("Century", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Change Password Form");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 20, 250, 23);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/changepass.jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 570, 330);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
        String Fname=null;
        String Lname= null;
        String User_Name=txtUName.getText();
        String Password =txtoldPwd.getText();
        String NewPwd  = txtNewPWD.getText();
        String ConfirmNewPwd=txtconfirmPwd.getText();
        String Address= null;
        String Country= null;
        String Gender= null;
        String Nic=    null;
        int    TeleNo= 0;
        String Category= null;
        String Email=    null;
        String Date= null;
        String Job=null;

        int result=0;
        
        if(Password.equals(logDB.getPassword(User_Name))){
            
            if(NewPwd.equals(ConfirmNewPwd)){
                
                Register chg=new Register(Fname, Lname, Address, Country, Gender,Date, Nic, TeleNo, Category, Email, User_Name, NewPwd, Job);
                result=logDB.changePassword(chg);
                
            }else{
                JOptionPane.showMessageDialog(rootPane, "Confirm Password does not match with New password"); //help messages
            }
            
        }else{
            JOptionPane.showMessageDialog(rootPane, "invalid User");  //help messages
        }
        
        if(result>0){
            
            JOptionPane.showMessageDialog(rootPane, "Password is changed");   //help message
        }else{
            JOptionPane.showMessageDialog(rootPane, "Password is not changed");   //help message
        }
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        // TODO add your handling code here:
         txtNewPWD.setText("");
         txtoldPwd.setText("");
        txtUName.setText("");
        txtconfirmPwd.setText("");
        
    }//GEN-LAST:event_btnclearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangePassword_Frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangePassword_Frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangePassword_Frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangePassword_Frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ChangePassword_Frm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btnupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPasswordField txtNewPWD;
    private javax.swing.JTextField txtUName;
    private javax.swing.JPasswordField txtconfirmPwd;
    private javax.swing.JPasswordField txtoldPwd;
    // End of variables declaration//GEN-END:variables
}
