/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import CONTROLLER.*;
import MODEL.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author MASS MNM
 */
public class PlayersCategory_Frm extends javax.swing.JFrame {
 private Player_RoleDB RoleDB;
 
Connection con=null;
ResultSet rs=null;
PreparedStatement pst=null;
    /**
     * Creates new form PlayersCategory_Frm
     */
    public PlayersCategory_Frm() {
        initComponents();
       con = new DBConnection().getConnection();
        RoleDB= new Player_RoleDB();
        
         ArrayList<PLayer_Role> RList=RoleDB.getPlayerRole();
         
        for(PLayer_Role u:RList){
            cmbroleid.addItem(u.getRole_ID());   
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtpcategory = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        btnadd = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtrolename = new javax.swing.JTextField();
        cmbroleid = new javax.swing.JComboBox<>();
        btnupdate = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(515, 300));
        setMinimumSize(new java.awt.Dimension(515, 300));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Player Role");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 140, 102, 29);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Player Category");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 180, 100, 30);
        getContentPane().add(txtpcategory);
        txtpcategory.setBounds(160, 180, 184, 30);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(10, 50, 480, 10);

        btnadd.setText("ADD");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });
        getContentPane().add(btnadd);
        btnadd.setBounds(390, 100, 90, 30);

        btndelete.setText("DELETE");
        getContentPane().add(btndelete);
        btndelete.setBounds(390, 180, 90, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Role ID");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 100, 110, 30);
        getContentPane().add(txtrolename);
        txtrolename.setBounds(160, 140, 185, 30);

        cmbroleid.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Role ID" }));
        cmbroleid.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cmbroleidPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        cmbroleid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbroleidActionPerformed(evt);
            }
        });
        getContentPane().add(cmbroleid);
        cmbroleid.setBounds(160, 100, 185, 30);

        btnupdate.setText("UPDATE");
        getContentPane().add(btnupdate);
        btnupdate.setBounds(390, 140, 90, 30);

        jLabel4.setFont(new java.awt.Font("Century", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Players Category");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(160, 10, 190, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/plyrCat.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 520, 300);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:
        String Role_id= cmbroleid.getSelectedItem().toString();
        String RoleName= txtrolename.getText();
        String Category= txtpcategory.getText();
        
        PlayerCategory catg= new PlayerCategory(Role_id, RoleName, Category);
        
        int result=RoleDB.addCategory(catg);
            
            if(result>0){
                JOptionPane.showMessageDialog(rootPane, "Player Category is added");
            }else{
                JOptionPane.showMessageDialog(rootPane, "Player Category is not added");
            }  
    }//GEN-LAST:event_btnaddActionPerformed

    private void cmbroleidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbroleidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbroleidActionPerformed

    private void cmbroleidPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cmbroleidPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        
         String category= cmbroleid.getSelectedItem().toString();
       String sql= "select * from player_role  where Role_ID=?";
        
        try{
        
              pst=con.prepareStatement(sql);
              pst.setString(1, category);
              rs=pst.executeQuery();
      
            while(rs.next()){
                String add1=rs.getString("Role_Name");
              
                   
                
                  
             //   cmbtow.addItem("ma");
                txtrolename.setText(add1);

              }  
        
          }catch(Exception e)
          {
            JOptionPane.showMessageDialog(null, e);
          }
    }//GEN-LAST:event_cmbroleidPopupMenuWillBecomeInvisible

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlayersCategory_Frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlayersCategory_Frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlayersCategory_Frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlayersCategory_Frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlayersCategory_Frm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnupdate;
    private javax.swing.JComboBox<String> cmbroleid;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtpcategory;
    private javax.swing.JTextField txtrolename;
    // End of variables declaration//GEN-END:variables
}
