/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import MODEL.*;
import CONTROLLER.*;
/**
 *
 * @author MASS MNM
 */
public class ViewBowlerList_Frm extends javax.swing.JFrame {
private MasterDB MasterDB;
private DefaultTableModel tblModel;
    /**
     * Creates new form ViewBowlerList_Frm
     */
    public ViewBowlerList_Frm() {
        initComponents();
        
         MasterDB=new MasterDB();
        
        
        tblModel=new DefaultTableModel();
        tblbowler.setModel(tblModel);
        
        tblModel.addColumn("Team_Name");
        tblModel.addColumn("Player Name");
        tblModel.addColumn("Player Role");
        tblModel.addColumn("Total Match");
        tblModel.addColumn("Nationality");
        tblModel.addColumn("Total Wickets");
        tblModel.addColumn("Bowlig Economy");
        tblModel.addColumn("Bowling Average");
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnserch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblbowler = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        cmbbowler = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(870, 400));
        setMinimumSize(new java.awt.Dimension(870, 400));
        setPreferredSize(new java.awt.Dimension(870, 400));
        getContentPane().setLayout(null);

        btnserch.setBackground(new java.awt.Color(0, 0, 0));
        btnserch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnserch.setForeground(new java.awt.Color(255, 255, 255));
        btnserch.setText("SEARCH");
        btnserch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnserchActionPerformed(evt);
            }
        });
        getContentPane().add(btnserch);
        btnserch.setBounds(470, 70, 102, 30);

        tblbowler.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblbowler);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 130, 830, 220);

        jLabel2.setFont(new java.awt.Font("Century", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("View Bowlers");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(220, 10, 150, 25);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(10, 40, 560, 10);

        cmbbowler.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BOWLER" }));
        getContentPane().add(cmbbowler);
        cmbbowler.setBounds(300, 70, 150, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon("F:\\Final Project\\CricketTeam_Selection\\src\\IMAGES\\viewAll.jpg")); // NOI18N
        jLabel3.setText("jLabel3");
        jLabel3.setMaximumSize(new java.awt.Dimension(870, 572));
        jLabel3.setMinimumSize(new java.awt.Dimension(870, 572));
        jLabel3.setPreferredSize(new java.awt.Dimension(870, 572));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 860, 370);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnserchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnserchActionPerformed
        // TODO add your handling code here:
                                                             //information
          tblModel.setRowCount(0);
        String PRole=cmbbowler.getSelectedItem().toString();
        ArrayList<Team_Players> pList=MasterDB.GetTeam(PRole);
        
        for(Team_Players atn:pList){
            
           tblModel.addRow(new Object[]{atn.getTeam_Name(),atn.getPlayerName(), atn.getPlayerRole(),atn.getTotalMatchs(),atn.getNationality(),atn.getNoofwickets(),atn.getBowl_Economy(),atn.getBowl_Average()}); 
        }
    }//GEN-LAST:event_btnserchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewBowlerList_Frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewBowlerList_Frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewBowlerList_Frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewBowlerList_Frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewBowlerList_Frm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnserch;
    private javax.swing.JComboBox<String> cmbbowler;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tblbowler;
    // End of variables declaration//GEN-END:variables
}
